name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout repository
        run: | 
          docker login --username edg-surv --password ${{ secrets.G_TOKEN }} ghcr.io
          docker build . --tag ghcr.io/edgesurv:latest
          docker push ghcr.io/edgesurv:latest
          
